apiVersion: apps/v1
kind: Deployment
metadata:
  name: "flux-2048-deployment"
  namespace: "fluxdemo"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: "flux2048"
  template:
    metadata:
      labels:
        app: "flux2048"
    spec:
      restartPolicy: Always  
      containers:
      - image: rorymcleanaderas/docker-2048
        imagePullPolicy: Always
        name: "flux2048"
        ports:
        - containerPort: 80
