apiVersion: v1
kind: Service
metadata:
  name: "flux-2048-service"
  namespace: "fluxdemo"
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: LoadBalancer
  selector:
    app: "flux2048"
